### ISSUE TITLE
Don't block duplicate colours in a row

### ISSUE THREAD

**Issue by quozl** [cristian99garcia/mastermind-activity#1]
In the game rules for Mastermind it is possible and sometimes necessary for the player to repeat the same colour in a row.

See https://en.wikipedia.org/wiki/Mastermind_(board_game) photograph.

However, at the moment your source code does not allow this.

Hope that helps!

**Comment by cvgarciarea** [comment]
I just wanted make the game a bit more easy, and I still find it quite difficult.

**Comment by quozl** [comment]
It doesn't make it easier; I'm speaking of the repeating of the guess colours, not the repeating of the secret code colours.

**Comment by quozl** [comment]
You see, a common player strategy is to guess four reds in a row, which will give no result if there are no reds, or it will give one black if there is one red, or two blacks if there are two reds, and so on.  A guess with four of the same colour can never give white results.

**Comment by cvgarciarea** [comment]
@quozl Solved https://github.com/cristian99garcia/mastermind-activity/commit/202e0fed7eff33d9877264f60ce218285f5da6f6

**Comment by quozl** [comment]
Tested accdec4914acc588d2b66265f669171404940749 and the issue is fixed.
