### ISSUE TITLE
Black and white results swapped

### ISSUE THREAD

**Issue by quozl** [cristian99garcia/mastermind-activity#2]
According to the rules of the game elsewhere;

* black peg is to be shown for each exact match of colour and position,
* white peg is to be shown for each match of colour in the wrong position.

At the moment, `ResultBox.set_data` has this swapped.

Quoting Wikipedia;
> A colored or black key peg is placed for each code peg from the guess which is correct in both color and position. A white key peg indicates the existence of a correct color code peg placed in the wrong position.

**Comment by cvgarciarea** [comment]
@quozl Solved https://github.com/cristian99garcia/mastermind-activity/commit/1e3b30a3af0e80d676f9c62b7790695665103855

**Comment by quozl** [comment]
Tested accdec4914acc588d2b66265f669171404940749 and the issue is fixed.
