### ISSUE TITLE
Cannot remove a placed circle

### ISSUE THREAD

**Issue by quozl** [cristian99garcia/mastermind-activity#3]
When the player makes a mistake and wants to undo before pressing the tick (✓) button, the circle cannot be removed.  Previously it could be dragged to where it was dragged from.

**Comment by cvgarciarea** [comment]
Solved on https://github.com/cristian99garcia/mastermind-activity/commit/84c9d568e551883d06815d923a67000d9e36dc1b and https://github.com/cristian99garcia/mastermind-activity/commit/a5bbd661c5d47c778d3f996b4bcac4afb47c0c3e

**Comment by quozl** [comment]
Thanks, works fine.

![scrot](https://cloud.githubusercontent.com/assets/2936481/21868123/6cb91004-d8a5-11e6-85fb-18f0043dc2f3.png)
